analytics: {}
color:
  brandColors:
    - '#242c40'
    - '#e2e207'
    - '#31c0cf'
    - '#ffffff'
    - '#767b87'
  brandStrength: 0.837171
  lightness: 1
  rhythmicContrast: 0.524671
  saturation: 0.494243
cta: {}
layout_spectrum: 1
name: DataSphere
opengraph: {}
purpose: []
typography_spectrum: 0.815789
