name: DataSphere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48956
title: DataSphere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242c40'
    - '#e2e207'
    - '#31c0cf'
    - '#ffffff'
    - '#767b87'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
