name: DataSphere
favicon: null
layout_spectrum: 0.36725
typography_spectrum: 0.88571
title: DataSphere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242c40'
    - '#e2e207'
    - '#31c0cf'
    - '#ffffff'
    - '#767b87'
  brandStrength: 0.75
  lightness: 0.28056598734110594
  saturation: 0.4292207369580865
  rhythmicContrast: 0.5158662593457848
purpose: []
