name: DataSphere
favicon: null
layout_spectrum: 0.6324679295066744
typography_spectrum: 0.47270896122790873
title: DataSphere IT Services and Consultancy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.05286055197939277
  lightness: 0.28056598734110594
  saturation: 0.4292207369580865
  rhythmicContrast: 0.5158662593457848
purpose: []
