name: DataSphere
favicon: null
layout_spectrum: 0.36725
typography_spectrum: 0.88571
title: DataSphere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242c40'
    - '#e2e207'
    - '#31c0cf'
    - '#ffffff'
    - '#767b87'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
