analytics: {}
color:
  brandColors:
    - '#242c40'
    - '#e2e207'
    - '#31c0cf'
    - '#ffffff'
    - '#767b87'
  brandStrength: 0.75
  lightness: 0.125
  rhythmicContrast: 0.25
  saturation: 0.75
cta: {}
layout_spectrum: 0
name: DataSphere
opengraph: {}
purpose: []
typography_spectrum: 0.48956
